Bump the minor-and-patch group in /e2e with 2 updates (#448)
Bumps the minor-and-patch group in /e2e with 2 updates:
[@axe-core/playwright](https://github.com/dequelabs/axe-core-npm) and
[prettier](https://github.com/prettier/prettier).

Updates `@axe-core/playwright` from 4.10.1 to 4.11.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/dequelabs/axe-core-npm/releases"><code>@​axe-core/playwright</code>'s
releases</a>.</em></p>
<blockquote>
<h2>Release 4.11.1</h2>
<h3>Bug Fixes</h3>
<ul>
<li>reorder exports to place types first (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1261">#1261</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/40d22e3cd6381796d731802efc71bc21c924025e">40d22e3</a>),
closes <a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1243">#1243</a></li>
<li>Update axe-core to v4.11.1 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1271">#1271</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/77f577ed47510045e75b939fa97ac1d4f91b219b">77f577e</a>)</li>
</ul>
<h2>Release 4.11.0</h2>
<h3>Bug Fixes</h3>
<ul>
<li>Optimize AxeBuilder memory usage. (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1154">#1154</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/e53cd36d0770a8323577946b0438f058b87a0aad">e53cd36</a>),
closes <a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts/issues/L59">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts#L59</a>
<a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts/issues/L34">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts#L34</a></li>
<li>Update axe-core to v4.10.3 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1155">#1155</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/f8e3a14043c7288ca9373a5f1543ffd27cedf256">f8e3a14</a>)</li>
<li><strong>wdio:</strong> resolve blank navigation issue in WDIO v9 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1169">#1169</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/6505560d646ddc6db8a9b4cf772af08ff3f08dc3">6505560</a>)</li>
</ul>
<h3>Features</h3>
<ul>
<li>Update axe-core to v4.11.0 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1233">#1233</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/27584764815148bf902f29010cca0f4f2230cf46">2758476</a>)</li>
</ul>
<h2>Release 4.10.2</h2>
<ul>
<li>Optimize AxeBuilder memory usage in <a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1154">#1154</a></li>
<li>Update axe-core to v4.10.3 in <a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1155">#1155</a></li>
<li><strong>wdio:</strong> resolve blank navigation issue in WDIO v9 in
<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1169">#1169</a></li>
<li>chore: RC v4.10.2</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/dequelabs/axe-core-npm/blob/develop/CHANGELOG.md"><code>@​axe-core/playwright</code>'s
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/dequelabs/axe-core-npm/compare/v4.11.0...v4.11.1">4.11.1</a>
(2026-01-09)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>reorder exports to place types first (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1261">#1261</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/40d22e3cd6381796d731802efc71bc21c924025e">40d22e3</a>),
closes <a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1243">#1243</a></li>
<li>Update axe-core to v4.11.1 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1271">#1271</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/77f577ed47510045e75b939fa97ac1d4f91b219b">77f577e</a>)</li>
</ul>
<h1><a
href="https://github.com/dequelabs/axe-core-npm/compare/v4.10.1...v4.11.0">4.11.0</a>
(2025-10-14)</h1>
<h3>Bug Fixes</h3>
<ul>
<li>Optimize AxeBuilder memory usage. (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1154">#1154</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/e53cd36d0770a8323577946b0438f058b87a0aad">e53cd36</a>),
closes <a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts/issues/L59">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts#L59</a>
<a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts/issues/L34">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts#L34</a></li>
<li>Update axe-core to v4.10.3 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1155">#1155</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/f8e3a14043c7288ca9373a5f1543ffd27cedf256">f8e3a14</a>)</li>
<li><strong>wdio:</strong> resolve blank navigation issue in WDIO v9 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1169">#1169</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/6505560d646ddc6db8a9b4cf772af08ff3f08dc3">6505560</a>)</li>
</ul>
<h3>Features</h3>
<ul>
<li>Update axe-core to v4.11.0 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1233">#1233</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/27584764815148bf902f29010cca0f4f2230cf46">2758476</a>)</li>
</ul>
<h2><a
href="https://github.com/dequelabs/axe-core-npm/compare/v4.10.1...v4.10.2">4.10.2</a>
(2025-05-12)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>Optimize AxeBuilder memory usage. (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1154">#1154</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/e53cd36d0770a8323577946b0438f058b87a0aad">e53cd36</a>),
closes <a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts/issues/L59">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts#L59</a>
<a
href="https://github.com//github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts/issues/L34">/github.com/bensenescu/axe-core-npm/blob/develop/packages/puppeteer/src/utils.ts#L34</a></li>
<li>Update axe-core to v4.10.3 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1155">#1155</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/f8e3a14043c7288ca9373a5f1543ffd27cedf256">f8e3a14</a>)</li>
<li><strong>wdio:</strong> resolve blank navigation issue in WDIO v9 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1169">#1169</a>)
(<a
href="https://github.com/dequelabs/axe-core-npm/commit/6505560d646ddc6db8a9b4cf772af08ff3f08dc3">6505560</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/66a3106a704e1d446f23cb151f96363425f42d02"><code>66a3106</code></a>
chore(release): v4.11.1 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1275">#1275</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/9a07fd719927e8b89db98ee325a9f0219870ef16"><code>9a07fd7</code></a>
chore: RC v4.11.1 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1272">#1272</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/999a563ddec8c7b431ee17f5e6ef9b79831a0beb"><code>999a563</code></a>
chore: applying release changes</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/26e0d0b0630c9ea50eb34b7edc44dcb68eb02a6b"><code>26e0d0b</code></a>
chore: RC v4.11.1</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/77f577ed47510045e75b939fa97ac1d4f91b219b"><code>77f577e</code></a>
fix: Update axe-core to v4.11.1 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1271">#1271</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/40d22e3cd6381796d731802efc71bc21c924025e"><code>40d22e3</code></a>
fix: reorder exports to place types first (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1261">#1261</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/bd80a5f74be0274ce657dc654bf6d4aef6fc97e7"><code>bd80a5f</code></a>
chore: rebuild lockfile (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1266">#1266</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/a73c6a8d47fd5b4d5299e1a9128e0486eb68eb0d"><code>a73c6a8</code></a>
chore: bump the npm-low-risk group across 1 directory with 27 updates
(<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1265">#1265</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/a80460d75a5cab7c6257ec3c0d5a39900d4c08e2"><code>a80460d</code></a>
chore: bump <code>@​wdio/mocha-framework</code> from 8.39.0 to 9.20.1
(<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1256">#1256</a>)</li>
<li><a
href="https://github.com/dequelabs/axe-core-npm/commit/2199e1bd478465b580be7dc59f548942c52caaa5"><code>2199e1b</code></a>
chore: bump mocha from 9.2.2 to 11.7.5 (<a
href="https://redirect.github.com/dequelabs/axe-core-npm/issues/1257">#1257</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/dequelabs/axe-core-npm/compare/v4.10.1...v4.11.1">compare
view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by [GitHub Actions](<a
href="https://www.npmjs.com/~GitHub">https://www.npmjs.com/~GitHub</a>
Actions), a new releaser for <code>@​axe-core/playwright</code> since
your current version.</p>
</details>
<br />

Updates `prettier` from 3.5.3 to 3.8.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.8.2</h2>
<ul>
<li>Support Angular v21.2</li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#382">Changelog</a></p>
<h2>3.8.1</h2>
<ul>
<li>Include available <code>printers</code> in plugin type declarations
(<a
href="https://redirect.github.com/prettier/prettier/pull/18706">#18706</a>
by <a href="https://github.com/porada"><code>@​porada</code></a>)</li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#381">Changelog</a></p>
<h2>3.8.0</h2>
<ul>
<li>Support Angular v21.1</li>
</ul>
<p><a
href="https://github.com/prettier/prettier/compare/3.7.4...3.8.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2026/01/14/3.8.0">Release note
&quot;Prettier 3.8: Support for Angular v21.1&quot;</a></p>
<h2>3.7.4</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix comment in union type gets duplicated by <a
href="https://github.com/fisker"><code>@​fisker</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18393">prettier/prettier#18393</a></li>
<li>Fix unstable comment print in union type by <a
href="https://github.com/fisker"><code>@​fisker</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18395">prettier/prettier#18395</a></li>
<li>Avoid quote around LWC interpolations by <a
href="https://github.com/kovsu"><code>@​kovsu</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18383">prettier/prettier#18383</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#374">Changelog</a></p>
<h2>3.7.3</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix <code>prettier.getFileInfo()</code> change that breaks VSCode
extension by <a
href="https://github.com/fisker"><code>@​fisker</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18375">prettier/prettier#18375</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#373">Changelog</a></p>
<h2>3.7.2</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix string print when switching quotes by <a
href="https://github.com/fisker"><code>@​fisker</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18351">prettier/prettier#18351</a></li>
<li>Preserve quote for embedded HTML attribute values by <a
href="https://github.com/kovsu"><code>@​kovsu</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18352">prettier/prettier#18352</a></li>
<li>Fix comment in empty type literal by <a
href="https://github.com/fisker"><code>@​fisker</code></a> in <a
href="https://redirect.github.com/prettier/prettier/pull/18364">prettier/prettier#18364</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#372">Changelog</a></p>
<h2>3.7.1</h2>
<ul>
<li>Fix performance regression in doc printer (<a
href="https://redirect.github.com/prettier/prettier/pull/18342">#18342</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#371">Changelog</a></p>
<h2>3.7.0</h2>
<p><a
href="https://github.com/prettier/prettier/compare/3.6.2...3.7.0">diff</a></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.8.2</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.8.1...3.8.2">diff</a></p>
<h4>Angular: Support Angular v21.2 (<a
href="https://redirect.github.com/prettier/prettier/pull/18722">#18722</a>,
<a
href="https://redirect.github.com/prettier/prettier/pull/19034">#19034</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<p>Exhaustive typechecking with <code>@default never;</code></p>
<!-- raw HTML omitted -->
<pre lang="html"><code>&lt;!-- Input --&gt;
@switch (foo) {
  @case (1) {}
  @default never;
}
<p>&lt;!-- Prettier 3.8.1 --&gt;
SyntaxError: Incomplete block &quot;default never&quot;. If you meant to
write the @ character, you should use the &quot;&amp;<a
href="https://redirect.github.com/prettier/prettier/issues/64">#64</a>;&quot;
HTML entity instead. (3:3)</p>
<p>&lt;!-- Prettier 3.8.2 --&gt;
<a href="https://github.com/switch"><code>@​switch</code></a> (foo) {
<a href="https://github.com/case"><code>@​case</code></a> (1) {}
<a href="https://github.com/default"><code>@​default</code></a> never;
}
</code></pre></p>
<p><code>arrow function</code> and <code>instanceof</code>
expressions.</p>
<!-- raw HTML omitted -->
<pre lang="html"><code>&lt;!-- Input --&gt;
@let fn = (a) =&gt;        a?    1:2;
<p>{{ fn ( a         instanceof b)}}</p>
<p>&lt;!-- Prettier 3.8.1 --&gt;
<a href="https://github.com/let"><code>@​let</code></a> fn = (a) =&gt;
a? 1:2;</p>
<p>{{ fn ( a         instanceof b)}}</p>
<p>&lt;!-- Prettier 3.8.2 --&gt;
<a href="https://github.com/let"><code>@​let</code></a> fn = (a) =&gt;
(a ? 1 : 2);</p>
<p>{{ fn(a instanceof b) }}
</code></pre></p>
<h1>3.8.1</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.8.0...3.8.1">diff</a></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/b31557cf331a02acf83e7e29d1001b070189a0d9"><code>b31557c</code></a>
Release 3.8.2</li>
<li><a
href="https://github.com/prettier/prettier/commit/96bbaeda0525bf758e464aed2f939d739a85c315"><code>96bbaed</code></a>
Support Angular v21.2 (<a
href="https://redirect.github.com/prettier/prettier/issues/18722">#18722</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/881360b92b3cfa39ffa0c0ee03bb4319079849a6"><code>881360b</code></a>
Support <code>default never</code> in Angular v21.2 (<a
href="https://redirect.github.com/prettier/prettier/issues/19034">#19034</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/07d67240f7a0f2d65014e00395b342bbec5db31b"><code>07d6724</code></a>
Bump Prettier dependency to 3.8.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/8b4a53ab3daddfe9c10c52fd5785a6a718770c34"><code>8b4a53a</code></a>
Clean changelog_unreleased</li>
<li><a
href="https://github.com/prettier/prettier/commit/90983f40dce5e20beea4e5618b5e0426a6a7f4f0"><code>90983f4</code></a>
Release 3.8.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/57f702f7656e6fc03873f8121480c321b2f44c8c"><code>57f702f</code></a>
Include available <code>printers</code> in plugin type declarations (<a
href="https://redirect.github.com/prettier/prettier/issues/18706">#18706</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/bece82785141274c12956b0af3bae77a44ae3a9e"><code>bece827</code></a>
Revert change in release script</li>
<li><a
href="https://github.com/prettier/prettier/commit/82a4ab26f1e7fccd0041272de12a3c6b942e622b"><code>82a4ab2</code></a>
Bump Prettier dependency to 3.8.0</li>
<li><a
href="https://github.com/prettier/prettier/commit/5213ee463c653f47e1821de414a4f30573f83337"><code>5213ee4</code></a>
Clean changelog_unreleased</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.5.3...3.8.2">compare
view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by [GitHub Actions](<a
href="https://www.npmjs.com/~GitHub">https://www.npmjs.com/~GitHub</a>
Actions), a new releaser for prettier since your current version.</p>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>


Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>